name: ssq_mobile_app
description: Native Flutter app for the SSQ mobile experience.
publish_to: "none"
version: 0.1.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bootstrap/


